# Numpy tutorial

general purpose array processing package

### Array

Data structure with a same data type values

In [1]:
# Imoprt numpy
import numpy as np


In [2]:
list1=[1,2,3,4,5]

In [3]:
array1=np.array(list1)
array1

array([1, 2, 3, 4, 5])

In [4]:
type(array1)

numpy.ndarray

In [5]:
array1.shape

(5,)

In [21]:
list2=[1,2,3,10]
list3=[4,5,6,11]
list4=[7,8,9,12]
array2=np.array([list2,list3,list4])
array2

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 12]])

In [22]:
type(array2)

numpy.ndarray

In [23]:
array2.shape

(3, 4)

In [25]:
array2.reshape(4,3)

array([[ 1,  2,  3],
       [10,  4,  5],
       [ 6, 11,  7],
       [ 8,  9, 12]])

# Indexing

### Accessing the array elements

In [18]:
array3=np.array([1,2,3,4,5])

In [19]:
# One diamensional
array3[4]

5

In [20]:
array3

array([1, 2, 3, 4, 5])

In [26]:
array2[:,:]

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 12]])

In [29]:
# from 0th row to 2nd row
array2[0:2,:]

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11]])

In [32]:
# 1st and 3rd column
array2[:,0:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Create array with arange()

In [33]:
arr=np.arange(0,10)

In [34]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Copy() function and broadcasting

In [42]:
# Relpace no from mention index
arr[3:]=19
arr

array([ 0,  1,  2, 19, 19, 19, 19, 19, 19, 19])

In [44]:
arr_copy=arr.copy()
arr_copy

array([ 0,  1,  2, 19, 19, 19, 19, 19, 19, 19])

### Create array with arange()

In [37]:
#with step 3
arr1=np.arange(0,20,3)

In [38]:
arr1

array([ 0,  3,  6,  9, 12, 15, 18])

### Create array with linspace()

In [40]:
# it divides equally array
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [46]:
# one diamensional array with value 1
np.ones(4)

array([1., 1., 1., 1.])

In [52]:
# two diamnesional array with value 1
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [53]:
#random distribution
np.random.rand(3,4)

array([[0.74111153, 0.33480007, 0.93273421, 0.36589265],
       [0.79905068, 0.27481658, 0.36689433, 0.18647471],
       [0.59846321, 0.68382509, 0.57244495, 0.52531426]])

In [54]:
#Normal distribution
np.random.randn(3,4)

array([[-0.65472403,  0.56757804, -1.4847236 ,  1.29304865],
       [ 0.8220351 ,  1.18215055,  0.97784697,  1.18283826],
       [ 0.7807876 , -0.53561112, -1.21135883, -1.34561725]])

In [55]:
#any n random numbers between 0 to 100 
np.random.randint(0,100,12)

array([41, 37, 58, 70, 64, 25, 25, 68, 57, 48, 58,  0])

In [56]:
# Return random floats in the half open interval
np.random.random_sample((1,5))

array([[0.64509161, 0.03760349, 0.71487963, 0.32472955, 0.00831482]])