In [1]:
#Create array in numpy

In [2]:
#create array using np.array() method

import numpy as np

In [5]:
l1=[1,2,3,4,5,6]
print(l1)
print(type(l1))

[1, 2, 3, 4, 5, 6]
<class 'list'>


In [9]:
a1=np.array(l1)

In [10]:
print(a1)

[1 2 3 4 5 6]


In [11]:
print(type(a1))

<class 'numpy.ndarray'>


In [25]:
a2=np.array([12,14,14,15,16])

In [26]:
print(type(a2))

<class 'numpy.ndarray'>


In [27]:
#statistical function in numpy

max_el=np.max(a2)
max_el

16

In [28]:
min_el=np.min(a2)
min_el

12

In [29]:
mean=np.mean(a2)
mean

14.2

In [30]:
med=np.median(a2)
med

14.0

In [31]:
std=np.std(a2)
std

1.32664991614216

In [32]:
var=np.var(a2)
var

1.7600000000000002

In [34]:
avg=np.average(a2)
avg

14.2

In [37]:
#give one more attribute i.e.how much percentile do u want
percentile=np.percentile(a2,56)
percentile

14.24

In [36]:
ptp=np.ptp(a2)
ptp

4

In [38]:
arr1=np.array([1,2,3,4,5,6])

In [43]:
print(np.percentile(arr1,25))
print(np.percentile(arr1,50))
print(np.percentile(arr1,75))
print(np.mean(arr1))
print(np.median(arr1))

2.25
3.5
4.75
3.5
3.5


In [44]:
#generate array using linespace- i.e.how many elements do you want

In [49]:
arr2=np.linspace(2,20,8)

In [50]:
arr2

array([ 2.        ,  4.57142857,  7.14285714,  9.71428571, 12.28571429,
       14.85714286, 17.42857143, 20.        ])

In [51]:
#generte array using np.arrange -print elemetns by the constant differeance

In [53]:
arr3=np.arange(2,20,3)
arr3

array([ 2,  5,  8, 11, 14, 17])

In [55]:
arr4=np.ones((2,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.]])

In [56]:
arr5=np.zeros((2,3))
arr5

array([[0., 0., 0.],
       [0., 0., 0.]])

In [57]:
#generate array using random numbers

In [64]:
arr6=np.random.rand(2,3)
arr6

array([[0.45142481, 0.44921764, 0.26531207],
       [0.68086786, 0.89987573, 0.22956753]])

arr5.shape

In [65]:
arr5.shape

(2, 3)

In [67]:
arr5.size

6

In [71]:
###generate array using logspace